import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "../lib/auth";
import { requireAuth } from "../lib/auth";
import { ensureTenantMiddleware } from "../lib/tenant";
import trafficRouter from "./traffic";
import poiRouter from "./poi";
import populationRouter from "./population";
import stopsRouter from "./stops";
import routesBusRouter from "./routes-bus";
import analysisRouter from "./analysis";
import cronRouter from "./cron";
import gtfsUploadRouter from "./gtfs-upload";
import gtfsQueriesRouter from "./gtfs-queries";
import gtfsAnalysisRouter from "./gtfs-analysis";
import gtfsTravelRouter from "./gtfs-travel";
import adminRouter from "./admin";
import scenariosRouter from "./scenarios";
import intermodalRouter from "./intermodal";
import optimizerRouteRouter from "./optimizer-route";
import optimizerScheduleRouter from "./optimizer-schedule";
import serviceProgramRouter from "./service-program";
import driverShiftsRouter from "./driver-shifts";
import clustersRouter from "./clusters";
import coincidenceZonesRouter from "./coincidence-zones";
import weatherRouter from "./weather";
import faresRouter from "./fares";
import faresMinOdRouter from "./fares-min-od";
import faresNodeAssignmentRouter from "./fares-node-assignment";
import caronteRouter from "./caronte";
import depotsRouter from "./depots";
import deadheadsRouter from "./deadheads";
import intermodalOptimizerRouter from "./intermodal-optimizer";
import aiRouter from "./ai";
import planningRouter from "./planning";
import territoryRouter from "./territory";
import schedulingProjectsRouter from "../lib/scheduling-projects";
import scheduleSharesRouter from "../lib/schedule-shares";
import planningStudioRouter from "../lib/planning-studio";
import planningStudioImportRouter from "../lib/planning-studio-import";
import planningStudioClustersRouter from "../lib/planning-studio-clusters";
import planningStudioPeriodsRouter from "../lib/planning-studio-periods";
import planningStudioTripsExtRouter from "../lib/planning-studio-trips-ext";
import planningStudioNetworkRouter from "../lib/planning-studio-network";
import planningStudioMaterializeRouter from "../lib/planning-studio-materialize";
import planningStudioValidityRouter from "../lib/planning-studio-validity";
import planningStudioValidityCategoriesRouter from "../lib/planning-studio-validity-categories";
import planningStudioValidityUnitsRouter from "../lib/planning-studio-validity-units";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(cronRouter); // pubblico (webhook/job esterni)
router.use(caronteRouter); // pubblico: auth via Bearer CERBERO_API_KEY (validatore)

// ⛔ Tutto sotto qui richiede autenticazione + colonne tenant pronte
router.use(requireAuth);
router.use(ensureTenantMiddleware);

router.use(trafficRouter);
router.use(poiRouter);
router.use(populationRouter);
router.use(stopsRouter);
router.use(routesBusRouter);
router.use(analysisRouter);
router.use(gtfsUploadRouter);
router.use(gtfsQueriesRouter);
router.use(gtfsAnalysisRouter);
router.use(gtfsTravelRouter);
router.use(adminRouter);
router.use(scenariosRouter);
router.use(intermodalRouter);
router.use(intermodalOptimizerRouter);
router.use(optimizerRouteRouter);
router.use(optimizerScheduleRouter);
router.use(serviceProgramRouter);
router.use(driverShiftsRouter);
router.use(clustersRouter);
router.use(coincidenceZonesRouter);
router.use(weatherRouter);
router.use(faresRouter);
router.use(faresMinOdRouter);
router.use(faresNodeAssignmentRouter);
router.use(depotsRouter);
router.use(deadheadsRouter);
router.use(aiRouter);
router.use(planningRouter);
router.use(territoryRouter);
router.use(schedulingProjectsRouter);
router.use(scheduleSharesRouter);
router.use(planningStudioRouter);
router.use(planningStudioImportRouter);
router.use(planningStudioClustersRouter);
router.use(planningStudioPeriodsRouter);
router.use(planningStudioTripsExtRouter);
router.use(planningStudioNetworkRouter);
router.use(planningStudioMaterializeRouter);
router.use(planningStudioValidityRouter);
router.use(planningStudioValidityCategoriesRouter);
router.use(planningStudioValidityUnitsRouter);

export default router;
