import { Router, type IRouter } from "express";
import healthRouter from "./health";
import trafficRouter from "./traffic";
import poiRouter from "./poi";
import populationRouter from "./population";
import stopsRouter from "./stops";
import routesBusRouter from "./routes-bus";
import analysisRouter from "./analysis";
import cronRouter from "./cron";
import gtfsUploadRouter from "./gtfs-upload";
import gtfsQueriesRouter from "./gtfs-queries";
import gtfsAnalysisRouter from "./gtfs-analysis";
import gtfsTravelRouter from "./gtfs-travel";
import adminRouter from "./admin";
import scenariosRouter from "./scenarios";
import intermodalRouter from "./intermodal";
import optimizerRouteRouter from "./optimizer-route";
import optimizerScheduleRouter from "./optimizer-schedule";
import serviceProgramRouter from "./service-program";
import driverShiftsRouter from "./driver-shifts";
import clustersRouter from "./clusters";
import coincidenceZonesRouter from "./coincidence-zones";
import weatherRouter from "./weather";
import faresRouter from "./fares";
import depotsRouter from "./depots";
import deadheadsRouter from "./deadheads";
import intermodalOptimizerRouter from "./intermodal-optimizer";
import aiRouter from "./ai";
import planningRouter from "./planning";

const router: IRouter = Router();

router.use(healthRouter);
router.use(trafficRouter);
router.use(poiRouter);
router.use(populationRouter);
router.use(stopsRouter);
router.use(routesBusRouter);
router.use(analysisRouter);
router.use(cronRouter);
router.use(gtfsUploadRouter);
router.use(gtfsQueriesRouter);
router.use(gtfsAnalysisRouter);
router.use(gtfsTravelRouter);
router.use(adminRouter);
router.use(scenariosRouter);
router.use(intermodalRouter);
router.use(intermodalOptimizerRouter);
router.use(optimizerRouteRouter);
router.use(optimizerScheduleRouter);
router.use(serviceProgramRouter);
router.use(driverShiftsRouter);
router.use(clustersRouter);
router.use(coincidenceZonesRouter);
router.use(weatherRouter);
router.use(faresRouter);
router.use(depotsRouter);
router.use(deadheadsRouter);
router.use(aiRouter);
router.use(planningRouter);

export default router;
